### ISSUE TITLE
Creating branches if branch is missing?

### ISSUE THREAD

**Issue by pjordaan** [symplify/monorepo-split-github-action#26]
Hi I'm using this github action on my monorepo. Since it's still a WIP all I had is a main branch and I was pushing to other repositories to the main branch. Now I have a 1.0 branch so I can work on making a stable version and I run into issues with the monorepo split. 

In the workflow I added:
```
-
        name: Monorepo Split of ${{ matrix.package }} (no tag)
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: "symplify/monorepo-split-github-action@2.1"
        with:
          package_directory: 'packages/${{ matrix.package }}'
          repository_organization: '<organization name>'
          repository_name: '${{ matrix.package }}'
          user_name: "<username>"
          user_email: "<email>"
          branch: '${{ github.ref_name }}'
```

This fails however as the repository I'm pushing to has no 1.0 branch (yet). Which results in this error:

```
[NOTE] Adding git commit



[NOTE] Pushing git commit with "<commit message>" message to "1.0"

error: src refspec 1.0 does not match any
error: failed to push some refs to 'https://github.com/<repository-link>.git'


[NOTE] Changing directory from "/tmp/monorepo_split/build_directory" to "/github/workspace"
```

Do I need to manually add these branches to all the child repositories? Or can this be done automatically?
